WARNING 2023-06-25 01:03:09,944 django.request Bad Request: /api/instance/
WARNING 2023-06-25 01:03:25,464 django.request Bad Request: /api/instance/
WARNING 2023-06-25 01:55:10,009 django.request Bad Request: /api/instance/2bc154db-072e-49f2-8a3b-6309479e8d17/redisgraph/check-module-loaded/
ERROR 2023-06-25 01:55:12,504 redisinsight Unknown command error from redis instance:
Traceback (most recent call last):
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/redisai/views.py", line 40, in _wrapped_view
  File "./redisinsight/redisai/views.py", line 224, in scripts_view
  File "./redisinsight/redisai/services.py", line 206, in list_scripts
  File "./redisinsight/redisai/services.py", line 185, in _list_scripts
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `AI._SCRIPTSCAN`, with args beginning with: 
ERROR 2023-06-25 01:55:12,507 redisinsight Unknown command error from redis instance:
Traceback (most recent call last):
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/redisai/views.py", line 40, in _wrapped_view
  File "./redisinsight/redisai/views.py", line 85, in models_view
  File "./redisinsight/redisai/services.py", line 181, in list_models
  File "./redisinsight/redisai/services.py", line 157, in _list_models
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `AI._MODELSCAN`, with args beginning with: 
ERROR 2023-06-25 01:55:12,515 django.request Unknown Status Code: /api/instance/2bc154db-072e-49f2-8a3b-6309479e8d17/redisai/scripts/
ERROR 2023-06-25 01:55:12,515 django.request Unknown Status Code: /api/instance/2bc154db-072e-49f2-8a3b-6309479e8d17/redisai/models/
WARNING 2023-06-25 01:55:13,157 django.request Bad Request: /api/instance/2bc154db-072e-49f2-8a3b-6309479e8d17/redistimeseries/module-info/
WARNING 2023-06-25 01:55:13,674 django.request Bad Request: /api/instance/2bc154db-072e-49f2-8a3b-6309479e8d17/check-redisearch-module-loaded/
